### ISSUE TITLE
Some gulp tasks error

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks_api#21]
OS X latest.  Started with `npm install`.   If we don't need these tasks let's just destroy them.

* `gulp apijson` fails
* `gulp apiyaml` fails

Preceeding both with `npx` also fails.

**Comment by LocoDelAssembly** [comment]
@mjy could you provide your terminal output? I cannot replicate apijson in neither Ubuntu nor MacOS. apiyaml does endeed fail in both Ubuntu and MacOS. Just pushed fix.

```terminal
$npx gulp apijson
[11:18:25] Using gulpfile ~/src/taxonworks_api/gulpfile.js
[11:18:25] Starting 'apijson'...
(node:967) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[11:18:26] Finished 'apijson' after 1.22 s
$npx gulp apiyaml
[11:18:36] Using gulpfile ~/src/taxonworks_api/gulpfile.js
[11:18:36] Starting 'apiyaml'...
[11:18:37] 'apiyaml' errored after 742 ms
[11:18:37] Error: Cannot find module 'js-yaml'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at raml2html (/Users/hernan/src/taxonworks_api/gulpfile.js:41:18)
    at /Users/hernan/src/taxonworks_api/gulpfile.js:109:11
    at taskWrapper (/Users/hernan/src/taxonworks_api/node_modules/undertaker/lib/set-task.js:13:15)
    at bound (domain.js:395:14)
    at runBound (domain.js:408:12)
    at asyncRunner (/Users/hernan/src/taxonworks_api/node_modules/async-done/index.js:55:18)
```

**Comment by mjy** [comment]
I can no longer replicate.  Closing.  Thanks for the update.
